# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import zipfile

## Library options

In [22]:
pd.set_option('display.max_columns', 500)

# Gather

In [2]:
# zipfile name
zip_name = "world-foodfeed-production.zip"

In [4]:
# zipfile's elements
zip_elements = []

In [6]:
# extract zipfile and gather its elements
with zipfile.ZipFile(zip_name, 'r') as _zip:
    _zip.extractall()
    zip_elements = _zip.namelist()

In [7]:
# csv name
csv_name = "FAO.csv"

In [51]:
#read csv
df = pd.read_csv(csv_name, encoding = "latin-1")

## Test

Check whether there is a change in the zipfile content since the last time

In [52]:
old_content = [csv_name]

In [53]:
# Checker - Must be True
old_content == zip_elements

True

# Clean & Assess

## Copy DataFrames

In [72]:
df_clean = df.copy()

## Assess

In [73]:
df_clean.head(10)

,Area Abbreviation,Area Code,Area,Item Code,Item,Element Code,Element,Unit,latitude,longitude,Y1961,Y1962,Y1963,Y1964,Y1965,Y1966,Y1967,Y1968,Y1969,Y1970,Y1971,Y1972,Y1973,Y1974,Y1975,Y1976,Y1977,Y1978,Y1979,Y1980,Y1981,Y1982,Y1983,Y1984,Y1985,Y1986,Y1987,Y1988,Y1989,Y1990,Y1991,Y1992,Y1993,Y1994,Y1995,Y1996,Y1997,Y1998,Y1999,Y2000,Y2001,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013
0,AFG,2,Afghanistan,2511,Wheat and products,5142,Food,1000 tonnes,33.94,67.71,1928.0,1904.0,1666.0,1950.0,2001.0,1808.0,2053.0,2045.0,2154.0,1819.0,1963.0,2215.0,2310.0,2335.0,2434.0,2512.0,2282.0,2454.0,2443.0,2129.0,2133.0,2068.0,1994.0,1851.0,1791.0,1683.0,2194.0,1801.0,1754.0,1640.0,1539.0,1582.0,1840.0,1855.0,1853.0,2177.0,2343.0,2407.0,2463.0,2600.0,2668.0,2776.0,3095.0,3249.0,3486.0,3704.0,4164.0,4252.0,4538.0,4605.0,4711.0,4810,4895
1,AFG,2,Afghanistan,2805,Rice (Milled Equivalent),5142,Food,1000 tonnes,33.94,67.71,183.0,183.0,182.0,220.0,220.0,195.0,231.0,235.0,238.0,213.0,205.0,233.0,246.0,246.0,255.0,263.0,235.0,254.0,270.0,259.0,248.0,217.0,217.0,197.0,186.0,200.0,193.0,202.0,191.0,199.0,197.0,249.0,218.0,260.0,319.0,254.0,326.0,347.0,270.0,372.0,411.0,448.0,460.0,419.0,445.0,546.0,455.0,490.0,415.0,442.0,476.0,425,422
2,AFG,2,Afghanistan,2513,Barley and products,5521,Feed,1000 tonnes,33.94,67.71,76.0,76.0,76.0,76.0,76.0,75.0,71.0,72.0,73.0,74.0,71.0,70.0,72.0,76.0,77.0,80.0,60.0,65.0,64.0,64.0,60.0,55.0,53.0,51.0,48.0,46.0,46.0,47.0,46.0,43.0,43.0,40.0,50.0,46.0,41.0,44.0,50.0,48.0,43.0,26.0,29.0,70.0,48.0,58.0,236.0,262.0,263.0,230.0,379.0,315.0,203.0,367,360
3,AFG,2,Afghanistan,2513,Barley and products,5142,Food,1000 tonnes,33.94,67.71,237.0,237.0,237.0,238.0,238.0,237.0,225.0,227.0,230.0,234.0,223.0,219.0,225.0,240.0,244.0,255.0,185.0,203.0,198.0,202.0,189.0,174.0,167.0,160.0,151.0,145.0,145.0,148.0,145.0,135.0,132.0,120.0,155.0,143.0,125.0,138.0,159.0,154.0,141.0,84.0,83.0,122.0,144.0,185.0,43.0,44.0,48.0,62.0,55.0,60.0,72.0,78,89
4,AFG,2,Afghanistan,2514,Maize and products,5521,Feed,1000 tonnes,33.94,67.71,210.0,210.0,214.0,216.0,216.0,216.0,235.0,232.0,236.0,200.0,201.0,216.0,228.0,231.0,234.0,240.0,228.0,234.0,228.0,226.0,210.0,199.0,192.0,182.0,173.0,170.0,154.0,148.0,137.0,144.0,126.0,90.0,141.0,150.0,159.0,108.0,90.0,99.0,72.0,35.0,48.0,89.0,63.0,120.0,208.0,233.0,249.0,247.0,195.0,178.0,191.0,200,200
5,AFG,2,Afghanistan,2514,Maize and products,5142,Food,1000 tonnes,33.94,67.71,403.0,403.0,410.0,415.0,415.0,413.0,454.0,448.0,455.0,383.0,386.0,416.0,439.0,445.0,451.0,463.0,439.0,451.0,440.0,437.0,407.0,384.0,371.0,353.0,334.0,330.0,298.0,287.0,265.0,279.0,245.0,170.0,272.0,289.0,310.0,209.0,173.0,192.0,141.0,66.0,93.0,170.0,117.0,231.0,67.0,82.0,67.0,69.0,71.0,82.0,73.0,77,76
6,AFG,2,Afghanistan,2517,Millet and products,5142,Food,1000 tonnes,33.94,67.71,17.0,18.0,19.0,20.0,21.0,22.0,23.0,24.0,25.0,26.0,26.0,27.0,27.0,28.0,29.0,37.0,32.0,33.0,31.0,31.0,29.0,27.0,28.0,26.0,25.0,23.0,23.0,23.0,23.0,24.0,24.0,18.0,22.0,20.0,21.0,17.0,20.0,21.0,17.0,20.0,20.0,18.0,16.0,15.0,21.0,11.0,19.0,21.0,18.0,14.0,14.0,14,12
7,AFG,2,Afghanistan,2520,"Cereals, Other",5142,Food,1000 tonnes,33.94,67.71,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
8,AFG,2,Afghanistan,2531,Potatoes and products,5142,Food,1000 tonnes,33.94,67.71,111.0,97.0,103.0,110.0,113.0,117.0,128.0,130.0,134.0,125.0,147.0,138.0,143.0,160.0,169.0,324.0,176.0,225.0,232.0,240.0,247.0,248.0,242.0,235.0,226.0,217.0,196.0,198.0,184.0,205.0,203.0,210.0,210.0,211.0,212.0,213.0,214.0,214.0,217.0,219.0,215.0,217.0,347.0,276.0,294.0,294.0,260.0,242.0,250.0,192.0,169.0,196,230
9,AFG,2,Afghanistan,2536,Sugar cane,5521,Feed,1000 tonnes,33.94,67.71,45.0,45.0,45.0,45.0,31.0,14.0,19.0,30.0,34.0,15.0,0.0,0.0,28.0,32.0,20.0,28.0,24.0,24.0,34.0,61.0,50.0,43.0,38.0,46.0,23.0,25.0,3.0,45.0,54.0,47.0,29.0,29.0,29.0,29.0,29.0,29.0,28.0,28.0,28.0,29.0,29.0,29.0,51.0,50.0,29.0,61.0,65.0,54.0,114.0,83.0,83.0,69,81

## Define  the Problem

Tere is no Id column. It is necessary for testing because we will melt later.

## Code

In [74]:
# generate the Ids
Id_column = df_clean.index +1

In [75]:
# add the id column to the dataframe
df_clean.insert(0, "SupplyId", Id_column)

## Test

In [76]:
df_clean.head()

,SupplyId,Area Abbreviation,Area Code,Area,Item Code,Item,Element Code,Element,Unit,latitude,longitude,Y1961,Y1962,Y1963,Y1964,Y1965,Y1966,Y1967,Y1968,Y1969,Y1970,Y1971,Y1972,Y1973,Y1974,Y1975,Y1976,Y1977,Y1978,Y1979,Y1980,Y1981,Y1982,Y1983,Y1984,Y1985,Y1986,Y1987,Y1988,Y1989,Y1990,Y1991,Y1992,Y1993,Y1994,Y1995,Y1996,Y1997,Y1998,Y1999,Y2000,Y2001,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013
0,1,AFG,2,Afghanistan,2511,Wheat and products,5142,Food,1000 tonnes,33.94,67.71,1928.0,1904.0,1666.0,1950.0,2001.0,1808.0,2053.0,2045.0,2154.0,1819.0,1963.0,2215.0,2310.0,2335.0,2434.0,2512.0,2282.0,2454.0,2443.0,2129.0,2133.0,2068.0,1994.0,1851.0,1791.0,1683.0,2194.0,1801.0,1754.0,1640.0,1539.0,1582.0,1840.0,1855.0,1853.0,2177.0,2343.0,2407.0,2463.0,2600.0,2668.0,2776.0,3095.0,3249.0,3486.0,3704.0,4164.0,4252.0,4538.0,4605.0,4711.0,4810,4895
1,2,AFG,2,Afghanistan,2805,Rice (Milled Equivalent),5142,Food,1000 tonnes,33.94,67.71,183.0,183.0,182.0,220.0,220.0,195.0,231.0,235.0,238.0,213.0,205.0,233.0,246.0,246.0,255.0,263.0,235.0,254.0,270.0,259.0,248.0,217.0,217.0,197.0,186.0,200.0,193.0,202.0,191.0,199.0,197.0,249.0,218.0,260.0,319.0,254.0,326.0,347.0,270.0,372.0,411.0,448.0,460.0,419.0,445.0,546.0,455.0,490.0,415.0,442.0,476.0,425,422
2,3,AFG,2,Afghanistan,2513,Barley and products,5521,Feed,1000 tonnes,33.94,67.71,76.0,76.0,76.0,76.0,76.0,75.0,71.0,72.0,73.0,74.0,71.0,70.0,72.0,76.0,77.0,80.0,60.0,65.0,64.0,64.0,60.0,55.0,53.0,51.0,48.0,46.0,46.0,47.0,46.0,43.0,43.0,40.0,50.0,46.0,41.0,44.0,50.0,48.0,43.0,26.0,29.0,70.0,48.0,58.0,236.0,262.0,263.0,230.0,379.0,315.0,203.0,367,360
3,4,AFG,2,Afghanistan,2513,Barley and products,5142,Food,1000 tonnes,33.94,67.71,237.0,237.0,237.0,238.0,238.0,237.0,225.0,227.0,230.0,234.0,223.0,219.0,225.0,240.0,244.0,255.0,185.0,203.0,198.0,202.0,189.0,174.0,167.0,160.0,151.0,145.0,145.0,148.0,145.0,135.0,132.0,120.0,155.0,143.0,125.0,138.0,159.0,154.0,141.0,84.0,83.0,122.0,144.0,185.0,43.0,44.0,48.0,62.0,55.0,60.0,72.0,78,89
4,5,AFG,2,Afghanistan,2514,Maize and products,5521,Feed,1000 tonnes,33.94,67.71,210.0,210.0,214.0,216.0,216.0,216.0,235.0,232.0,236.0,200.0,201.0,216.0,228.0,231.0,234.0,240.0,228.0,234.0,228.0,226.0,210.0,199.0,192.0,182.0,173.0,170.0,154.0,148.0,137.0,144.0,126.0,90.0,141.0,150.0,159.0,108.0,90.0,99.0,72.0,35.0,48.0,89.0,63.0,120.0,208.0,233.0,249.0,247.0,195.0,178.0,191.0,200,200

## Assess

In [81]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21477 entries, 0 to 21476
Data columns (total 64 columns):
SupplyId             21477 non-null int64
Area Abbreviation    21477 non-null object
Area Code            21477 non-null int64
Area                 21477 non-null object
Item Code            21477 non-null int64
Item                 21477 non-null object
Element Code         21477 non-null int64
Element              21477 non-null object
Unit                 21477 non-null object
latitude             21477 non-null float64
longitude            21477 non-null float64
Y1961                17938 non-null float64
Y1962                17938 non-null float64
Y1963                17938 non-null float64
Y1964                17938 non-null float64
Y1965                17938 non-null float64
Y1966                17938 non-null float64
Y1967                17938 non-null float64
Y1968                17938 non-null float64
Y1969                17938 non-null float64
Y1970                17938 non-null float64
Y1971                17938 non-null float64
Y1972                17938 non-null float64
Y1973                17938 non-null float64
Y1974                17938 non-null float64
Y1975                17938 non-null float64
Y1976                17938 non-null float64
Y1977                17938 non-null float64
Y1978                17938 non-null float64
Y1979                17938 non-null float64
Y1980                17938 non-null float64
Y1981                17938 non-null float64
Y1982                17938 non-null float64
Y1983                17938 non-null float64
Y1984                17938 non-null float64
Y1985                17938 non-null float64
Y1986                17938 non-null float64
Y1987                17938 non-null float64
Y1988                17938 non-null float64
Y1989                17938 non-null float64
Y1990                18062 non-null float64
Y1991                18062 non-null float64
Y1992                20490 non-null float64
Y1993                20865 non-null float64
Y1994                20865 non-null float64
Y1995                20865 non-null float64
Y1996                20865 non-null float64
Y1997                20865 non-null float64
Y1998                20865 non-null float64
Y1999                20865 non-null float64
Y2000                21128 non-null float64
Y2001                21128 non-null float64
Y2002                21128 non-null float64
Y2003                21128 non-null float64
Y2004                21128 non-null float64
Y2005                21128 non-null float64
Y2006                21373 non-null float64
Y2007                21373 non-null float64
Y2008                21373 non-null float64
Y2009                21373 non-null float64
Y2010                21373 non-null float64
Y2011                21373 non-null float64
Y2012                21477 non-null int64
Y2013                21477 non-null int64
dtypes: float64(53), int64(6), object(5)
memory usage: 10.5+ MB

In [82]:
df_clean["Y1978"].value_counts()

0.0         7066
1.0         1267
2.0          698
3.0          536
4.0          393
5.0          296
6.0          251
7.0          237
8.0          209
10.0         181
9.0          178
11.0         161
12.0         148
15.0         125
14.0         119
18.0         104
13.0         101
17.0          95
20.0          91
16.0          90
19.0          84
22.0          83
26.0          76
23.0          70
31.0          68
21.0          64
27.0          64
28.0          63
24.0          62
25.0          60
            ...
3754.0         1
91621.0        1
726.0          1
1204.0         1
2418.0         1
4566.0         1
5217.0         1
2430.0         1
766.0          1
626.0          1
4029.0         1
2227.0         1
1310.0         1
12490.0        1
6269.0         1
1665.0         1
4795.0         1
2009.0         1
10751.0        1
2302.0         1
6755.0         1
1181.0         1
142403.0       1
1484.0         1
2548.0         1
849.0          1
2097.0         1
2255.0         1
1451.0         1
6015.0         1
Name: Y1978, Length: 1463, dtype: int64

In [83]:
df_clean[np.isnan(df_clean["Y1978"])]

,SupplyId,Area Abbreviation,Area Code,Area,Item Code,Item,Element Code,Element,Unit,latitude,longitude,Y1961,Y1962,Y1963,Y1964,Y1965,Y1966,Y1967,Y1968,Y1969,Y1970,Y1971,Y1972,Y1973,Y1974,Y1975,Y1976,Y1977,Y1978,Y1979,Y1980,Y1981,Y1982,Y1983,Y1984,Y1985,Y1986,Y1987,Y1988,Y1989,Y1990,Y1991,Y1992,Y1993,Y1994,Y1995,Y1996,Y1997,Y1998,Y1999,Y2000,Y2001,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013
679,680,ARM,1,Armenia,2511,Wheat and products,5521,Feed,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,21.0,24.0,25.0,10.0,32.0,58.0,55.0,78.0,20.0,20.0,42.0,69.0,59.0,46.0,67.0,57.0,56.0,61.0,65.0,92,93
680,681,ARM,1,Armenia,2511,Wheat and products,5142,Food,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,539.0,544.0,476.0,497.0,455.0,503.0,495.0,489.0,481.0,461.0,429.0,443.0,490.0,433.0,445.0,412.0,428.0,391.0,372.0,386.0,377,389
681,682,ARM,1,Armenia,2805,Rice (Milled Equivalent),5521,Feed,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
682,683,ARM,1,Armenia,2805,Rice (Milled Equivalent),5142,Food,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,19.0,17.0,10.0,10.0,7.0,11.0,10.0,10.0,9.0,13.0,12.0,11.0,14.0,17.0,15.0,13.0,13.0,11.0,9.0,9,9
683,684,ARM,1,Armenia,2513,Barley and products,5521,Feed,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115.0,63.0,58.0,61.0,79.0,31.0,48.0,46.0,15.0,65.0,40.0,53.0,68.0,57.0,33.0,86.0,76.0,102.0,86.0,124.0,121,137
684,685,ARM,1,Armenia,2513,Barley and products,5142,Food,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,1.0,4.0,3.0,3.0,5.0,5.0,7.0,7.0,0.0,8.0,8.0,0.0,0.0,7.0,11.0,7.0,1,0
685,686,ARM,1,Armenia,2514,Maize and products,5521,Feed,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4.0,4.0,4.0,5.0,9.0,9.0,12.0,18.0,22.0,32.0,31.0,52.0,13.0,16.0,91.0,80.0,58.0,57.0,66.0,53,96
686,687,ARM,1,Armenia,2514,Maize and products,5142,Food,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
687,688,ARM,1,Armenia,2515,Rye and products,5521,Feed,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,10.0,10.0,10.0,0.0,0.0,13.0,16.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1,1
688,689,ARM,1,Armenia,2515,Rye and products,5142,Food,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
689,690,ARM,1,Armenia,2516,Oats,5521,Feed,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,0.0,0.0,2.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,2.0,3.0,3,4
690,691,ARM,1,Armenia,2516,Oats,5142,Food,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1,1
691,692,ARM,1,Armenia,2517,Millet and products,5521,Feed,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9,0
692,693,ARM,1,Armenia,2518,Sorghum and products,5521,Feed,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
693,694,ARM,1,Armenia,2520,"Cereals, Other",5521,Feed,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6.0,1.0,1.0,0.0,1.0,1,1
694,695,ARM,1,Armenia,2520,"Cereals, Other",5142,Food,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,1.0,1.0,57.0,26.0,25.0,18.0,2.0,7.0,5.0,7.0,5.0,5.0,5.0,18.0,6.0,4.0,6.0,25.0,5,6
695,696,ARM,1,Armenia,2532,Cassava and products,5521,Feed,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
696,697,ARM,1,Armenia,2531,Potatoes and products,5521,Feed,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,25.0,3.0,2.0,27.0,25.0,25.0,25.0,15.0,18.0,65.0,70.0,144.0,137.0,140.0,182.0,214.0,193.0,88.0,173.0,236,225
697,698,ARM,1,Armenia,2531,Potatoes and products,5142,Food,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,221.0,246.0,263.0,294.0,258.0,237.0,260.0,261.0,196.0,199.0,153.0,146.0,182.0,214.0,195.0,153.0,150.0,170.0,143.0,131.0,133,134
698,699,ARM,1,Armenia,2534,"Roots, Other",5521,Feed,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
699,700,ARM,1,Armenia,2537,Sugar beet,5521,Feed,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,2.0,1.0,2.0,1.0,3.0,1.0,1.0,0,1
700,701,ARM,1,Armenia,2542,Sugar (Raw Equivalent),5142,Food,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.0,76.0,71.0,65.0,69.0,67.0,78.0,76.0,75.0,78.0,85.0,96.0,93.0,102.0,100.0,101.0,106.0,102.0,119.0,107.0,100,98
701,702,ARM,1,Armenia,2543,"Sweeteners, Other",5142,Food,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,6.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,1.0,0.0,7,5
702,703,ARM,1,Armenia,2745,Honey,5142,Food,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2,2
703,704,ARM,1,Armenia,2546,Beans,5521,Feed,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,4.0,3.0,5.0,5.0,3.0,3.0,4.0,3.0,3.0,4.0,5.0,4.0,4.0,5.0,5.0,5.0,4.0,5.0,4,5
704,705,ARM,1,Armenia,2547,Peas,5521,Feed,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,3.0,2.0,1.0,1.0,2.0,2.0,3.0,3.0,2.0,3.0,2.0,2,2
705,706,ARM,1,Armenia,2549,"Pulses, Other and products",5521,Feed,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,7.0,2.0,0.0,1.0,0.0,0.0,1.0,1.0,3.0,1.0,1.0,2.0,2.0,3.0,2.0,2.0,4.0,3.0,2,3
706,707,ARM,1,Armenia,2549,"Pulses, Other and products",5142,Food,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
707,708,ARM,1,Armenia,2551,Nuts and products,5142,Food,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,6.0,5.0,5.0,5.0,5.0,5,6
708,709,ARM,1,Armenia,2555,Soyabeans,5521,Feed,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,20.0,17.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,1.0,0.0,0.0,0.0,6.0,0.0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20752,20753,UZB,235,Uzbekistan,2680,Infant food,5142,Food,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,4.0,0.0,5.0,5.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1,1
20753,20754,UZB,235,Uzbekistan,2905,Cereals - Excluding Beer,5521,Feed,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,677.0,406.0,295.0,253.0,217.0,108.0,114.0,129.0,155.0,226.0,1014.0,1189.0,721.0,1817.0,1998.0,2727.0,2467.0,2968.0,3129.0,3298.0,3742,3564
20754,20755,UZB,235,Uzbekistan,2905,Cereals - Excluding Beer,5142,Food,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4479.0,4529.0,4617.0,4587.0,4498.0,4363.0,4103.0,4331.0,4182.0,4160.0,4350.0,4650.0,4708.0,4807.0,4839.0,4617.0,4945.0,5052.0,5110.0,5139.0,5195,5266
20755,20756,UZB,235,Uzbekistan,2907,Starchy Roots,5521,Feed,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,3.0,4.0,9.0,11.0,44.0,38.0,39.0,76.0,103.0,222.0,391,523
20756,20757,UZB,235,Uzbekistan,2907,Starchy Roots,5142,Food,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,581.0,550.0,562.0,527.0,630.0,845.0,849.0,785.0,675.0,695.0,721.0,770.0,825.0,850.0,918.0,1069.0,1258.0,1320.0,1460.0,1480.0,1500,1510
20757,20758,UZB,235,Uzbekistan,2908,Sugar Crops,5521,Feed,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,22.0,21.0,13.0,2.0,82.0,33.0,53.0,19.0,15.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
20758,20759,UZB,235,Uzbekistan,2909,Sugar & Sweeteners,5142,Food,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,276.0,294.0,228.0,254.0,360.0,343.0,477.0,406.0,379.0,249.0,172.0,115.0,124.0,215.0,329.0,546.0,329.0,286.0,287.0,287.0,288,292
20759,20760,UZB,235,Uzbekistan,2911,Pulses,5521,Feed,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,6.0,5.0,6.0,6.0,5.0,15.0,19.0,3.0,15.0,10.0,7.0,11.0,8.0,14.0,17.0,16.0,22.0,16.0,12.0,21,35
20760,20761,UZB,235,Uzbekistan,2911,Pulses,5142,Food,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1,1
20761,20762,UZB,235,Uzbekistan,2912,Treenuts,5142,Food,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,13.0,13.0,14.0,14.0,14.0,16.0,19.0,17.0,24.0,27.0,32.0,34.0,34.0,42.0,29.0,29.0,30.0,31.0,30.0,32,33
20762,20763,UZB,235,Uzbekistan,2913,Oilcrops,5521,Feed,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,321.0,689.0,373.0,524.0,520.0,807.0,622.0,502.0,142.0,416.0,391.0,199.0,589.0,523.0,394.0,481.0,601.0,114.0,315.0,383.0,355,324
20763,20764,UZB,235,Uzbekistan,2913,Oilcrops,5142,Food,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,0.0,3.0,4.0,4.0,4.0,0.0,0.0,2.0,4.0,4.0,3.0,2.0,5,4
20764,20765,UZB,235,Uzbekistan,2914,Vegetable Oils,5142,Food,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,259.0,291.0,297.0,315.0,307.0,317.0,324.0,287.0,301.0,301.0,272.0,268.0,274.0,291.0,289.0,299.0,288.0,266.0,276.0,287.0,309,309
20765,20766,UZB,235,Uzbekistan,2918,Vegetables,5521,Feed,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,694.0,378.0,147.0,21.0,23.0,34.0,46.0,146.0,113.0,92.0,97.0,136.0,188.0,251.0,349.0,466.0,634.0,719.0,955.0,1015.0,1080,1249
20766,20767,UZB,235,Uzbekistan,2918,Vegetables,5142,Food,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3299.0,2925.0,2948.0,2776.0,2577.0,2385.0,2468.0,2871.0,2688.0,2909.0,3000.0,3366.0,3238.0,3381.0,4185.0,4594.0,5198.0,5611.0,6074.0,6613.0,7564,8082
20767,20768,UZB,235,Uzbekistan,2919,Fruits - Excluding Wine,5521,Feed,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,207.0,128.0,32.0,141.0,213.0,59.0,6.0,2.0,21.0,14.0,12.0,8.0,8.0,3.0,5.0,6.0,27.0,87.0,95.0,79.0,90,127
20768,20769,UZB,235,Uzbekistan,2919,Fruits - Excluding Wine,5142,Food,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,682.0,568.0,609.0,790.0,758.0,724.0,676.0,646.0,949.0,981.0,1028.0,832.0,993.0,1079.0,1448.0,1538.0,1693.0,1875.0,2108.0,2159.0,2422,2638
20769,20770,UZB,235,Uzbekistan,2922,Stimulants,5142,Food,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,13.0,30.0,15.0,7.0,16.0,10.0,12.0,22.0,26.0,23.0,4.0,22.0,26.0,22.0,24.0,30.0,29.0,28.0,29.0,35,35
20770,20771,UZB,235,Uzbekistan,2923,Spices,5142,Food,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,3.0,3.0,4.0,3.0,4.0,4.0,3.0,3.0,2.0,3.0,3.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,5,7
20771,20772,UZB,235,Uzbekistan,2924,Alcoholic Beverages,5142,Food,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158.0,146.0,168.0,193.0,180.0,167.0,162.0,168.0,161.0,146.0,157.0,166.0,172.0,179.0,204.0,206.0,232.0,289.0,362.0,367.0,335,331
20772,20773,UZB,235,Uzbekistan,2943,Meat,5142,Food,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,528.0,529.0,667.0,676.0,630.0,664.0,674.0,507.0,522.0,512.0,525.0,579.0,619.0,655.0,696.0,690.0,729.0,771.0,826.0,956.0,958,1029
20773,20774,UZB,235,Uzbekistan,2945,Offals,5142,Food,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.0,66.0,75.0,81.0,73.0,75.0,81.0,75.0,80.0,76.0,73.0,79.0,80.0,82.0,84.0,83.0,83.0,87.0,87.0,88.0,91,94
20774,20775,UZB,235,Uzbekistan,2946,Animal fats,5142,Food,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0,34.0,36.0,32.0,25.0,23.0,27.0,25.0,26.0,18.0,24.0,25.0,26.0,29.0,29.0,31.0,39.0,49.0,54.0,65.0,63,66
20775,20776,UZB,235,Uzbekistan,2949,Eggs,5142,Food,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96.0,91.0,79.0,67.0,57.0,58.0,63.0,67.0,68.0,69.0,70.0,84.0,97.0,102.0,109.0,112.0,113.0,124.0,131.0,135.0,143,151
20776,20777,UZB,235,Uzbekistan,2948,Milk - Excluding Butter,5521,Feed,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,450.0,393.0,348.0,426.0,193.0,168.0,106.0,159.0,215.0,223.0,230.0,617.0,724.0,858.0,1143.0,1273.0,1709.0,2056.0,2434.0,3022.0,3562,4125
20777,20778,UZB,235,Uzbekistan,2948,Milk - Excluding Butter,5142,Food,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3211.0,3403.0,3392.0,3203.0,3245.0,3319.0,3435.0,3379.0,3418.0,3419.0,3522.0,3521.0,3569.0,3709.0,3726.0,3830.0,3726.0,3743.0,3742.0,3770.0,3782,3785
20778,20779,UZB,235,Uzbekistan,2960,"Fish, Seafood",5521,Feed,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,3.0,2.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,5.0,5.0,7.0,10,20
20779,20780,UZB,235,Uzbekistan,2960,"Fish, Seafood",5142,Food,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0,21.0,15.0,15.0,7.0,12.0,13.0,11.0,10.0,8.0,7.0,6.0,7.0,8.0,7.0,8.0,12.0,13.0,15.0,19.0,22,22
20780,20781,UZB,235,Uzbekistan,2961,"Aquatic Products, Other",5142,Food,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
20781,20782,UZB,235,Uzbekistan,2928,Miscellaneous,5142,Food,1000 tonnes,41.38,64.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,4.0,0.0,5.0,5.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1,1

Row with SupplyId 680 will be our test row for seeing what happened with the empty columns

## Define  the Problem

Variables in the column headers. Year variables are separated in different columns, it should be one. Melting will solve the problem. After that, delete the original year columns from the table.

## Code

In [77]:
# Gather the erronous column names
erronous_column_names = list(df_clean)[11:]
correct_column_names = list(df_clean)[0:10]

In [78]:
# Melting the variable columns into one
df_supply_clean = pd.melt(df_clean, id_vars = "SupplyId", value_vars = erronous_column_names, var_name = "Year", value_name = "Supply")

In [101]:
# Delete original year columns
df_clean.drop(axis = 1, columns = erronous_column_names, inplace = True)

## Test

In [79]:
df_supply_clean

         SupplyId   Year  Supply
0               1  Y1961  1928.0
1               2  Y1961   183.0
2               3  Y1961    76.0
3               4  Y1961   237.0
4               5  Y1961   210.0
5               6  Y1961   403.0
6               7  Y1961    17.0
7               8  Y1961     0.0
8               9  Y1961   111.0
9              10  Y1961    45.0
10             11  Y1961     0.0
11             12  Y1961    45.0
12             13  Y1961     0.0
13             14  Y1961     2.0
14             15  Y1961     1.0
15             16  Y1961    15.0
16             17  Y1961     2.0
17             18  Y1961     0.0
18             19  Y1961    10.0
19             20  Y1961     0.0
20             21  Y1961     0.0
21             22  Y1961     0.0
22             23  Y1961     3.0
23             24  Y1961     0.0
24             25  Y1961     4.0
25             26  Y1961     0.0
26             27  Y1961     2.0
27             28  Y1961     0.0
28             29  Y1961     0.0
29             30  Y1961     0.0
...           ...    ...     ...
1138251     21448  Y2013     0.0
1138252     21449  Y2013     0.0
1138253     21450  Y2013     0.0
1138254     21451  Y2013     0.0
1138255     21452  Y2013     0.0
1138256     21453  Y2013    55.0
1138257     21454  Y2013  2016.0
1138258     21455  Y2013   276.0
1138259     21456  Y2013     0.0
1138260     21457  Y2013   416.0
1138261     21458  Y2013    55.0
1138262     21459  Y2013     3.0
1138263     21460  Y2013    30.0
1138264     21461  Y2013    38.0
1138265     21462  Y2013   160.0
1138266     21463  Y2013   227.0
1138267     21464  Y2013   217.0
1138268     21465  Y2013    10.0
1138269     21466  Y2013    12.0
1138270     21467  Y2013   516.0
1138271     21468  Y2013   258.0
1138272     21469  Y2013    22.0
1138273     21470  Y2013    20.0
1138274     21471  Y2013    25.0
1138275     21472  Y2013    31.0
1138276     21473  Y2013   451.0
1138277     21474  Y2013    15.0
1138278     21475  Y2013    40.0
1138279     21476  Y2013     0.0
1138280     21477  Y2013     0.0

[1138281 rows x 3 columns]

In [84]:
df_supply_clean[df_supply_clean["SupplyId"] == 1]

         SupplyId   Year  Supply
0               1  Y1961  1928.0
21477           1  Y1962  1904.0
42954           1  Y1963  1666.0
64431           1  Y1964  1950.0
85908           1  Y1965  2001.0
107385          1  Y1966  1808.0
128862          1  Y1967  2053.0
150339          1  Y1968  2045.0
171816          1  Y1969  2154.0
193293          1  Y1970  1819.0
214770          1  Y1971  1963.0
236247          1  Y1972  2215.0
257724          1  Y1973  2310.0
279201          1  Y1974  2335.0
300678          1  Y1975  2434.0
322155          1  Y1976  2512.0
343632          1  Y1977  2282.0
365109          1  Y1978  2454.0
386586          1  Y1979  2443.0
408063          1  Y1980  2129.0
429540          1  Y1981  2133.0
451017          1  Y1982  2068.0
472494          1  Y1983  1994.0
493971          1  Y1984  1851.0
515448          1  Y1985  1791.0
536925          1  Y1986  1683.0
558402          1  Y1987  2194.0
579879          1  Y1988  1801.0
601356          1  Y1989  1754.0
622833          1  Y1990  1640.0
644310          1  Y1991  1539.0
665787          1  Y1992  1582.0
687264          1  Y1993  1840.0
708741          1  Y1994  1855.0
730218          1  Y1995  1853.0
751695          1  Y1996  2177.0
773172          1  Y1997  2343.0
794649          1  Y1998  2407.0
816126          1  Y1999  2463.0
837603          1  Y2000  2600.0
859080          1  Y2001  2668.0
880557          1  Y2002  2776.0
902034          1  Y2003  3095.0
923511          1  Y2004  3249.0
944988          1  Y2005  3486.0
966465          1  Y2006  3704.0
987942          1  Y2007  4164.0
1009419         1  Y2008  4252.0
1030896         1  Y2009  4538.0
1052373         1  Y2010  4605.0
1073850         1  Y2011  4711.0
1095327         1  Y2012  4810.0
1116804         1  Y2013  4895.0

In [85]:
df_supply_clean[df_supply_clean["SupplyId"] == 680]

         SupplyId   Year  Supply
679           680  Y1961     NaN
22156         680  Y1962     NaN
43633         680  Y1963     NaN
65110         680  Y1964     NaN
86587         680  Y1965     NaN
108064        680  Y1966     NaN
129541        680  Y1967     NaN
151018        680  Y1968     NaN
172495        680  Y1969     NaN
193972        680  Y1970     NaN
215449        680  Y1971     NaN
236926        680  Y1972     NaN
258403        680  Y1973     NaN
279880        680  Y1974     NaN
301357        680  Y1975     NaN
322834        680  Y1976     NaN
344311        680  Y1977     NaN
365788        680  Y1978     NaN
387265        680  Y1979     NaN
408742        680  Y1980     NaN
430219        680  Y1981     NaN
451696        680  Y1982     NaN
473173        680  Y1983     NaN
494650        680  Y1984     NaN
516127        680  Y1985     NaN
537604        680  Y1986     NaN
559081        680  Y1987     NaN
580558        680  Y1988     NaN
602035        680  Y1989     NaN
623512        680  Y1990     NaN
644989        680  Y1991     NaN
666466        680  Y1992    14.0
687943        680  Y1993    21.0
709420        680  Y1994    24.0
730897        680  Y1995    25.0
752374        680  Y1996    10.0
773851        680  Y1997    32.0
795328        680  Y1998    58.0
816805        680  Y1999    55.0
838282        680  Y2000    78.0
859759        680  Y2001    20.0
881236        680  Y2002    20.0
902713        680  Y2003    42.0
924190        680  Y2004    69.0
945667        680  Y2005    59.0
967144        680  Y2006    46.0
988621        680  Y2007    67.0
1010098       680  Y2008    57.0
1031575       680  Y2009    56.0
1053052       680  Y2010    61.0
1074529       680  Y2011    65.0
1096006       680  Y2012    92.0
1117483       680  Y2013    93.0

In [102]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21477 entries, 0 to 21476
Data columns (total 11 columns):
SupplyId             21477 non-null int64
Area Abbreviation    21477 non-null object
Area Code            21477 non-null int64
Area                 21477 non-null object
Item Code            21477 non-null int64
Item                 21477 non-null object
Element Code         21477 non-null int64
Element              21477 non-null object
Unit                 21477 non-null object
latitude             21477 non-null float64
longitude            21477 non-null float64
dtypes: float64(2), int64(4), object(5)
memory usage: 1.8+ MB

## Assess

Every unit is in 1000 tonnes. It is redundant information, so we can write this into the column name

In [87]:
df_clean["Unit"].value_counts()

1000 tonnes    21477
Name: Unit, dtype: int64

## Define the Problem

Because every unit is in 1,000 tonnes, it would be better to have this information in the Supply column header. Ten delete the Unit column.

## Code

In [90]:
# Rename Supply column header
df_supply_clean.rename(columns =
                      {
                          "Supply" : "Supply1000Tonnes"
                      }, inplace = True)

In [108]:
# Delete Unit column
df_clean.drop( columns = "Unit", axis = 1, inplace = True)

## Test

In [91]:
df_supply_clean.head()

   SupplyId   Year  Supply1000Tonnes
0         1  Y1961            1928.0
1         2  Y1961             183.0
2         3  Y1961              76.0
3         4  Y1961             237.0
4         5  Y1961             210.0

In [109]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21477 entries, 0 to 21476
Data columns (total 10 columns):
SupplyId            21477 non-null int64
AreaAbbreviation    21477 non-null object
AreaCode            21477 non-null int64
Area                21477 non-null object
Item Code           21477 non-null int64
Item                21477 non-null object
Element Code        21477 non-null int64
Element             21477 non-null object
Latitude            21477 non-null float64
Longitude           21477 non-null float64
dtypes: float64(2), int64(4), object(4)
memory usage: 1.6+ MB

## Define the Problem

Year should be numerical and there is an Y letter in the value. Delete first the Y letter, then change its type to in64.

## Code

In [92]:
# Delete Y letter
df_supply_clean["Year"] = df_supply_clean["Year"].str[1:]

In [93]:
# Convert from string to integer
df_supply_clean["Year"] = df_supply_clean["Year"].astype("int64")

## Test

In [94]:
df_supply_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1138281 entries, 0 to 1138280
Data columns (total 3 columns):
SupplyId            1138281 non-null int64
Year                1138281 non-null int64
Supply1000Tonnes    1020831 non-null float64
dtypes: float64(1), int64(2)
memory usage: 26.1 MB

In [95]:
df_supply_clean.sample(5)

        SupplyId  Year  Supply1000Tonnes
780415      7244  1997              15.0
29096       7620  1962             406.0
29618       8142  1962               4.0
210755     17463  1970               NaN
114067      6683  1966               0.0

## Assess

In [96]:
df_clean.sample(15)

,SupplyId,Area Abbreviation,Area Code,Area,Item Code,Item,Element Code,Element,Unit,latitude,longitude,Y1961,Y1962,Y1963,Y1964,Y1965,Y1966,Y1967,Y1968,Y1969,Y1970,Y1971,Y1972,Y1973,Y1974,Y1975,Y1976,Y1977,Y1978,Y1979,Y1980,Y1981,Y1982,Y1983,Y1984,Y1985,Y1986,Y1987,Y1988,Y1989,Y1990,Y1991,Y1992,Y1993,Y1994,Y1995,Y1996,Y1997,Y1998,Y1999,Y2000,Y2001,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013
462,463,ATG,8,Antigua and Barbuda,2555,Soyabeans,5142,Food,1000 tonnes,17.06,-61.80,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
7485,7486,GEO,73,Georgia,2737,"Fats, Animals, Raw",5142,Food,1000 tonnes,42.32,43.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,6.0,6.0,6.0,6.0,7.0,6.0,6.0,6.0,7.0,8.0,8.0,10.0,10.0,9.0,9.0,8.0,8.0,11.0,13.0,14,14
16378,16379,KNA,188,Saint Kitts and Nevis,2766,Cephalopods,5142,Food,1000 tonnes,17.36,-62.78,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
6838,6839,FIN,67,Finland,2619,Dates,5142,Food,1000 tonnes,61.92,25.75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
15644,15645,PRT,174,Portugal,2922,Stimulants,5142,Food,1000 tonnes,39.40,-8.22,14.0,14.0,15.0,13.0,16.0,15.0,17.0,19.0,21.0,20.0,24.0,27.0,26.0,24.0,19.0,26.0,16.0,13.0,16.0,15.0,19.0,24.0,23.0,24.0,29.0,27.0,35.0,37.0,38.0,43.0,46.0,48.0,52.0,53.0,48.0,53.0,51.0,57.0,66.0,62.0,63.0,63.0,62.0,65.0,65.0,67.0,71.0,71.0,69.0,72.0,75.0,80,85
5888,5889,DMA,55,Dominica,2960,"Fish, Seafood",5142,Food,1000 tonnes,15.41,-61.37,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2,1
18451,18452,SWE,210,Sweden,2533,Sweet potatoes,5142,Food,1000 tonnes,60.13,18.64,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1,1
19739,19740,TKM,213,Turkmenistan,2928,Miscellaneous,5142,Food,1000 tonnes,38.97,59.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1,1
21379,21380,ZWE,181,Zimbabwe,2547,Peas,5142,Food,1000 tonnes,-19.02,29.15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,8.0,9.0,8.0,8.0,24.0,21.0,18.0,14.0,13,14
3281,3282,CMR,32,Cameroon,2536,Sugar cane,5142,Food,1000 tonnes,7.37,12.35,47.0,46.0,108.0,35.0,39.0,113.0,73.0,92.0,49.0,56.0,22.0,60.0,65.0,83.0,201.0,207.0,211.0,227.0,229.0,252.0,317.0,269.0,187.0,727.0,704.0,825.0,681.0,588.0,448.0,588.0,580.0,569.0,659.0,639.0,659.0,539.0,539.0,539.0,539.0,539.0,538.0,407.0,386.0,435.0,443.0,329.0,227.0,252.0,435.0,435.0,441.0,245,195
5067,5068,CUB,49,Cuba,2549,"Pulses, Other and products",5142,Food,1000 tonnes,21.52,-77.78,71.0,38.0,63.0,57.0,60.0,68.0,74.0,71.0,79.0,85.0,81.0,88.0,94.0,108.0,75.0,104.0,114.0,104.0,85.0,102.0,101.0,117.0,105.0,122.0,125.0,92.0,132.0,108.0,125.0,98.0,109.0,159.0,115.0,165.0,126.0,131.0,148.0,162.0,130.0,88.0,65.0,56.0,19.0,41.0,71.0,69.0,69.0,149.0,104.0,25.0,34.0,37,64
15028,15029,PRY,169,Paraguay,2563,Olives (including preserved),5142,Food,1000 tonnes,-23.44,-58.44,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1,1
11453,11454,LBR,123,Liberia,2782,"Fish, Liver Oil",5142,Food,1000 tonnes,6.43,-9.43,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
21336,21337,ZMB,251,Zambia,2912,Treenuts,5142,Food,1000 tonnes,-13.13,27.85,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0,0
16100,16101,RUS,185,Russian Federation,2558,Rape and Mustardseed,5521,Feed,1000 tonnes,61.52,105.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.0,99.0,73.0,74.0,49.0,19.0,10.0,10.0,8.0,6.0,6.0,75.0,79.0,120.0,283.0,299.0,343.0,178.0,158.0,613.0,479,676

In [97]:
df_clean.Item.value_counts()

Milk - Excluding Butter         558
Eggs                            360
Cereals - Excluding Beer        347
Fish, Seafood                   337
Maize and products              333
Pelagic Fish                    328
Oilcrops                        314
Starchy Roots                   309
Cereals, Other                  308
Animal fats                     280
Oats                            279
Barley and products             276
Wheat and products              273
Pulses                          261
Fish, Body Oil                  259
Vegetables, Other               258
Vegetables                      258
Pulses, Other and products      255
Rice (Milled Equivalent)        255
Potatoes and products           254
Oilcrops, Other                 250
Fruits - Excluding Wine         232
Cassava and products            225
Soyabeans                       223
Rye and products                223
Marine Fish, Other              219
Roots, Other                    213
Sugar & Sweeteners              203
Demersal Fish                   203
Sugar (Raw Equivalent)          197
                               ...
Grapefruit and products         162
Infant food                     161
Miscellaneous                   161
Cream                           159
Dates                           159
Olives (including preserved)    158
Groundnut Oil                   158
Maize Germ Oil                  158
Citrus, Other                   155
Pimento                         154
Sugar Crops                     141
Coconut Oil                     136
Aquatic Animals, Others         135
Plantains                       135
Cloves                          134
Sesameseed Oil                  129
Sesame seed                     125
Palm Oil                        124
Rape and Mustard Oil            121
Cottonseed Oil                  110
Sunflower seed                  106
Palmkernel Oil                   92
Yams                             90
Sugar cane                       87
Sugar beet                       66
Sugar non-centrifugal            32
Palm kernels                     24
Cottonseed                       21
Ricebran Oil                     18
Meat, Aquatic Mammals             3
Name: Item, Length: 115, dtype: int64

In [98]:
df_clean.Area.value_counts()

Spain                                    150
Italy                                    148
Germany                                  147
China, mainland                          146
Greece                                   143
Japan                                    143
United Kingdom                           143
Sweden                                   142
Philippines                              142
Hungary                                  142
Kazakhstan                               141
Switzerland                              141
Netherlands                              141
United States of America                 141
China, Taiwan Province of                141
Canada                                   140
Norway                                   140
South Africa                             140
France                                   140
Lithuania                                140
Austria                                  139
Romania                                  139
Denmark                                  139
Cuba                                     137
Brazil                                   137
Russian Federation                       137
Latvia                                   136
Belgium                                  136
Ireland                                  136
Poland                                   136
                                        ...
Guinea                                   112
Sierra Leone                             111
Dominica                                 111
Saint Vincent and the Grenadines         109
Angola                                   109
Viet Nam                                 109
Central African Republic                 109
Gambia                                   108
Rwanda                                   108
Samoa                                    108
Djibouti                                 107
Cabo Verde                               106
Sudan                                    104
Maldives                                 104
Chad                                     103
Bermuda                                  103
Tajikistan                               102
Lao People's Democratic Republic         102
Solomon Islands                          100
Saint Kitts and Nevis                     99
Liberia                                   99
Democratic People's Republic of Korea     97
Vanuatu                                   96
Kiribati                                  94
Guinea-Bissau                             91
Sao Tome and Principe                     91
Turkmenistan                              90
Timor-Leste                               86
Afghanistan                               83
Lesotho                                   75
Name: Area, Length: 174, dtype: int64

In [103]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21477 entries, 0 to 21476
Data columns (total 11 columns):
SupplyId             21477 non-null int64
Area Abbreviation    21477 non-null object
Area Code            21477 non-null int64
Area                 21477 non-null object
Item Code            21477 non-null int64
Item                 21477 non-null object
Element Code         21477 non-null int64
Element              21477 non-null object
Unit                 21477 non-null object
latitude             21477 non-null float64
longitude            21477 non-null float64
dtypes: float64(2), int64(4), object(5)
memory usage: 1.8+ MB

## Define the Problem

There are some column headers in the df_clean that is not in camelcase format. Change these names into the right ones.

## Code

In [105]:
df_clean.rename(columns =
               {
                   "Area Abbreviation" : "AreaAbbreviation",
                   "Area Code" : "AreaCode",
                   "latitude" : "Latitude",
                   "longitude" : "Longitude"
               }, inplace = True)

## Test

In [107]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21477 entries, 0 to 21476
Data columns (total 11 columns):
SupplyId            21477 non-null int64
AreaAbbreviation    21477 non-null object
AreaCode            21477 non-null int64
Area                21477 non-null object
Item Code           21477 non-null int64
Item                21477 non-null object
Element Code        21477 non-null int64
Element             21477 non-null object
Unit                21477 non-null object
Latitude            21477 non-null float64
Longitude           21477 non-null float64
dtypes: float64(2), int64(4), object(5)
memory usage: 1.8+ MB

# Store

In [110]:
# csv names
csv_supply_info = "supply_info_clean.csv"
csv_supply = "supply_clean.csv"

In [112]:
# Save files
df_clean.to_csv(csv_supply_info, index = False)
df_supply_clean.to_csv(csv_supply, index = False)

In [114]:
# new zip file name
zip_name = zip_name[:-4] + "_clean.zip"

In [119]:
# Files to save
files_to_save = [csv_supply_info, csv_supply]

In [121]:
#Compress files into a zipfile
with zipfile.ZipFile(zip_name, "w") as _zip:
    for i in range(len(files_to_save)):
        _zip.write(files_to_save[i])

# Source

Dataset source : www.kaggle.com